name: Test Python with pytest

on:
  workflow_dispatch:        # Permite ejecutar manualmente desde github
  #schedule:
    #- cron: '50 20 * * *'      # Ejecutar todos los dias horario UTC (-3 en Argentina)
    # (minuto) (hora) (dia del mes) (mes) (dia de la semana)
    # El intervalo minimo de ejecución de los flujos de trabajo programados es de 5 minutos !!!!
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar tests con pytest
        run: pytest
